# Generated by Django 4.0.3 on 2023-12-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimaterent', '0004_property_area_property_bhk_property_launch_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bhk',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_range',
            field=models.CharField(default='$0 - $0', max_length=100),
        ),
    ]
