# Generated by Django 4.0.3 on 2024-01-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimaterent', '0005_alter_property_bhk_alter_property_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='balconies',
            field=models.IntegerField(blank=True, null=True, verbose_name='Balconies'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Baths'),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bedrooms'),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Deposit Amount'),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Furnishing'),
        ),
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Garages'),
        ),
    ]
