# Generated by Django 4.0.3 on 2024-01-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimaterent', '0007_property_sale_or_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
