# Generated by Django 4.0.3 on 2024-01-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimaterent', '0010_alter_property_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_date', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
