# Generated by Django 4.0.3 on 2024-01-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimaterent', '0011_visitschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitschedule',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_schedules', to='ultimaterent.property'),
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=8),
        ),
    ]
