# Generated by Django 4.0.3 on 2024-01-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimaterent', '0013_property_location_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location_pin',
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=30, null=True),
        ),
    ]
