# Generated by Django 4.0.3 on 2024-01-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimaterent', '0014_remove_property_location_pin_property_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.AddField(
            model_name='property',
            name='location_pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
