# Generated by Django 4.0.3 on 2024-02-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimaterent', '0013_offer'),
        ('ultimaterent', '0016_offer'),
    ]

    operations = [
    ]
