# Generated by Django 4.0.3 on 2024-02-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimaterent', '0022_agent_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='password',
        ),
    ]
