# Generated by Django 4.0.3 on 2024-02-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimaterent', '0029_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
