# Generated by Django 4.0.3 on 2024-03-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimaterent', '0032_appointment_status_alter_property_price_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_range',
            field=models.CharField(default='0৳ - 0৳', max_length=100),
        ),
    ]
